// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.spt.workshop1.domain;

import com.spt.workshop1.domain.EmpType;
import com.spt.workshop1.domain.EmpTypeDataOnDemand;
import com.spt.workshop1.domain.EmpTypeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EmpTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EmpTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EmpTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EmpTypeIntegrationTest: @Transactional;
    
    @Autowired
    EmpTypeDataOnDemand EmpTypeIntegrationTest.dod;
    
    @Test
    public void EmpTypeIntegrationTest.testCountEmpTypes() {
        Assert.assertNotNull("Data on demand for 'EmpType' failed to initialize correctly", dod.getRandomEmpType());
        long count = EmpType.countEmpTypes();
        Assert.assertTrue("Counter for 'EmpType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EmpTypeIntegrationTest.testFindEmpType() {
        EmpType obj = dod.getRandomEmpType();
        Assert.assertNotNull("Data on demand for 'EmpType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EmpType' failed to provide an identifier", id);
        obj = EmpType.findEmpType(id);
        Assert.assertNotNull("Find method for 'EmpType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'EmpType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EmpTypeIntegrationTest.testFindAllEmpTypes() {
        Assert.assertNotNull("Data on demand for 'EmpType' failed to initialize correctly", dod.getRandomEmpType());
        long count = EmpType.countEmpTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'EmpType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<EmpType> result = EmpType.findAllEmpTypes();
        Assert.assertNotNull("Find all method for 'EmpType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'EmpType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EmpTypeIntegrationTest.testFindEmpTypeEntries() {
        Assert.assertNotNull("Data on demand for 'EmpType' failed to initialize correctly", dod.getRandomEmpType());
        long count = EmpType.countEmpTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<EmpType> result = EmpType.findEmpTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'EmpType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'EmpType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EmpTypeIntegrationTest.testFlush() {
        EmpType obj = dod.getRandomEmpType();
        Assert.assertNotNull("Data on demand for 'EmpType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EmpType' failed to provide an identifier", id);
        obj = EmpType.findEmpType(id);
        Assert.assertNotNull("Find method for 'EmpType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEmpType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'EmpType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmpTypeIntegrationTest.testMergeUpdate() {
        EmpType obj = dod.getRandomEmpType();
        Assert.assertNotNull("Data on demand for 'EmpType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EmpType' failed to provide an identifier", id);
        obj = EmpType.findEmpType(id);
        boolean modified =  dod.modifyEmpType(obj);
        Integer currentVersion = obj.getVersion();
        EmpType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'EmpType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmpTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'EmpType' failed to initialize correctly", dod.getRandomEmpType());
        EmpType obj = dod.getNewTransientEmpType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'EmpType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'EmpType' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'EmpType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EmpTypeIntegrationTest.testRemove() {
        EmpType obj = dod.getRandomEmpType();
        Assert.assertNotNull("Data on demand for 'EmpType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EmpType' failed to provide an identifier", id);
        obj = EmpType.findEmpType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'EmpType' with identifier '" + id + "'", EmpType.findEmpType(id));
    }
    
}
