// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.spt.workshop1.domain;

import com.spt.workshop1.domain.Employee;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Employee_Roo_Configurable {
    
    declare @type: Employee: @Configurable;
    
}
