// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.spt.workshop1.domain;

import com.spt.workshop1.domain.EmpType;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EmpType_Roo_Configurable {
    
    declare @type: EmpType: @Configurable;
    
}
